const albumList = [{
    cover: "https://f4.bcbits.com/img/a0845889841_16.jpg",
    color: "blue",
    name: "Out of the Blue",
    artists: "Blue Dish",
    description: "Drawing upon a vast array of influences - from Jazz to Blues - Blue Dish’s eclectic sound is seemingly boundless, defying genre at every moment.",
    credits: "<strong>Mixed + Mastered:</strong> Elie Mcafee-Hahn <br> <strong>Performed By:</strong> Elie Mcafee Hahn & Julie Bodian",
    youtube: "https://youtu.be/GOlXO-qs61M",
    spotify: "https://open.spotify.com/album/2aX2eODXtSYV9Sq2uD8J3a?si=l4XZLXdCRuW5wf3LeSHmvQ",
    bandcamp: "https://bluedish.bandcamp.com/",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-3Vh95brqXadydmOt-Q74EsA-t500x500.jpg",
    color: "purple",
    name: "Tetso Cube Light Ride",
    artists: "Elie Mcafee-Hahn",
    description: "Elie is cool :)",
    credits: "",
    youtube: "https://www.youtube.com/watch?v=H0u_aZUWL-w&ab_channel=baz%2abailey%2a",
    spotify: "",
    bandcamp: "https://bandcamp.com/elielielielielie",
    instagram: "https://www.instagram.com/ellie_modron_kurfwen/?hl=en"
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  },
  {
    cover: "https://i1.sndcdn.com/artworks-OmT5lbIsnIHrJLIw-9vVfJQ-t500x500.jpg",
    color: "green",
    name: "Birfth",
    artists: "Katarina Mazur",
    description: "Kat is fun and cool. This is about this so it's good like that. Listen to it :)",
    credits: "",
    youtube: "",
    spotify: "",
    bandcamp: "https://soundcloud.com/katmazur",
    instagram: ""
  }
];

module.exports = {
  albumList
};